//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Assets.Scripts.Interfaces;
namespace Assets.Scripts.Base
{
	public abstract class StateBase : IStateBase
	{
		public StateManager manager;

		public StateBase (StateManager sm){
			manager = sm;
		}

		public virtual void Init(){}
		public virtual void StateUpdate (){}
		public virtual void StateFixedUpdate (){}
		public virtual void StateGUI (){}
		public virtual void SceneLoaded(int level){}
		public virtual void DetectCollision2D (Collision2D collider, GameObject sender){}
		public virtual void MouseDown (GameObject gameObj){}
		public virtual void MouseUp (GameObject gameObj){}
		public virtual void TriggerEnter2D (Collider2D collider, GameObject sender){}
		public virtual void FinishLevel (){}
		public virtual void Recycle (){}
	}
}

