//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Assets.Scripts.Base;
using Assets.Scripts.Managers;
using Assets.Scripts.Misc;

namespace Assets.Scripts.States.Dust{

	public class DustLevel3 : PlayState{

		public DustLevel3 (StateManager sm) : base(sm) {

		}

		public override void Init (){
			base.Init ();

			// set next state
			manager.SetState (new DustLevel4 (manager));

			// set net level unlock
			unlockNextLevel = "dustlevel3lock";

			if (! SceneManager.IsSceneLoaded (SceneManager.Dust.LEVEL3)) {
				SceneManager.LoadScene (SceneManager.Dust.LEVEL3);
			}
		}
	}
}

