//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Assets.Scripts.Base;
using Assets.Scripts.Managers;
using Assets.Scripts.Misc;

namespace Assets.Scripts.States.Dust{
	
	public class DustLevel10 : DustPlay{

		public DustLevel10 (StateManager sm) : base(sm) {

		}

		public override void Init (){
			base.Init ();

			// set next state
			manager.SetState (new DustLevel10 (manager));

			if (! SceneManager.IsSceneLoaded (SceneManager.Dust.LEVEL10)) {
				SceneManager.LoadScene (SceneManager.Dust.LEVEL10);
			}
		}

		public override void FinishLevel (){
			base.FinishLevel ();
			
			// set net level unlock
			unlockNextLevel = "nightlevel0lock";
		}

		public override void SetNextState (){
			base.SetNextState ();

			// set next state
			manager.SetState (new WelcomeToNightState (manager));
		}

		public override void Restart (){
			base.Restart ();

			GameObject.Find (GameCenter.Dust.BIG_STONE).transform.localPosition = new Vector3 (72.31f, 0.3f, 19.56f);
			GameObject.Find (GameCenter.Dust.BIG_STONE).transform.localRotation = Quaternion.Euler (-90f, 0f, 0f);
			GameObject.Find (GameCenter.Dust.BIG_STONE).GetComponent<Rigidbody2D> ().isKinematic = false;
		}

		public override void Pause (){
			base.Pause ();
			GameObject.Find (GameCenter.Dust.BIG_STONE).GetComponent<Rigidbody2D> ().isKinematic = true;
		}

		public override void Resume (){
			base.Resume ();
			GameObject.Find (GameCenter.Dust.BIG_STONE).GetComponent<Rigidbody2D> ().isKinematic = false;
		}

		public override void Died (){
			base.Died ();
			GameObject.Find (GameCenter.Dust.BIG_STONE).GetComponent<Rigidbody2D> ().isKinematic = true;
		}
	}
}

