//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Assets.Scripts.Base;
using Assets.Scripts.Managers;

namespace Assets.Scripts.States.Dust{

	public class DustLevel1 : PlayState{

		public DustLevel1 (StateManager sm) : base(sm) {

		}
		public override void Init (){
			base.Init ();
			if (! SceneManager.IsSceneLoaded (SceneManager.Dust.LEVEL1)) {
				SceneManager.LoadScene (SceneManager.Dust.LEVEL1);
			}
		}

		public override void FinishLevel (){
			manager.SetState (new DustLevel2(manager));
			Debug.Log (manager.GetState ());
			base.FinishLevel ();
		}
	}
}

