//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Assets.Scripts.Base;
using Assets.Scripts.Managers;

namespace Assets.Scripts.States{

	public class DustLevels : LevelSelection{

		public DustLevels (StateManager sm) : base(sm){

		}

		public override void Init (){
			base.Init ();
			if (! SceneManager.IsSceneLoaded (SceneManager.LevelSelection.DUST)) {
				SceneManager.LoadScene(SceneManager.LevelSelection.DUST);
			}
		}

		public override void MouseDown (GameObject gameObj){
			base.MouseDown (gameObj);


		}

	}
}

