//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Assets.Scripts.Base;
using Assets.Scripts.Managers;
using Assets.Scripts.Misc;
using Assets.Scripts.States.Dust;

namespace Assets.Scripts.States{

	public class DustLevels : LevelSelection{

		public DustLevels (StateManager sm) : base(sm){

		}

		public override void Init (){
			base.Init ();

			// set current level selection
			currentSelection = DUST;

			if (! SceneManager.IsSceneLoaded (SceneManager.LevelSelection.DUST)) {
				SceneManager.LoadScene(SceneManager.LevelSelection.DUST);
			}
		}

		public override void MouseDown (GameObject gameObj){
			base.MouseDown (gameObj);

			// check level 1 is unlock
			if (gameObj.name.Equals (GameCenter.Levels.LEVEL0)) {
				if (! StorageManager.IsLevelLocked (DUST + "level0lock")){
					manager.SetState(new DustLevel1 (manager));
					ChangeState ();
				}
			}

			// check level 2 is unlock
			else if (gameObj.name.Equals (GameCenter.Levels.LEVEL1)) {
				if (! StorageManager.IsLevelLocked (DUST + "level1lock")){
					manager.SetState(new DustLevel2 (manager));
					ChangeState ();
				}
			}

			// check level 3 is unlock
			else if (gameObj.name.Equals (GameCenter.Levels.LEVEL2)) {
				if (! StorageManager.IsLevelLocked (DUST + "level2lock")){
					manager.SetState(new DustLevel3 (manager));
					ChangeState ();
				}
			}

			// check level 4 is unlock
			else if (gameObj.name.Equals (GameCenter.Levels.LEVEL3)) {
				if (! StorageManager.IsLevelLocked (DUST + "level3lock")){
					manager.SetState(new DustLevel4 (manager));
					ChangeState ();
				}
			}

		}


	}
}

