//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Assets.Scripts.Base;

namespace Assets.Scripts.States{

	public class LevelSelection : StateBase{

		public LevelSelection (StateManager sm) : base(sm){

		}

	}
}

