//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

namespace Assets.Scripts.Misc{

	public class GameCenter{

		// generals names
		public static readonly string GAME_MANAGER = "GameManager";
		public static readonly string MAIN_CAMERA = "MainCamera";
		public static readonly string LEFT_CONTROL = "LeftControl";
		public static readonly string RIGHT_CONTROL = "RightControl";
		public static readonly string EXIT = "Exit";
		public static readonly string PLAY = "Play";
		public static readonly string PIPE = "Pipe";
		public static readonly string SEAT = "Seat";
		public static readonly string CYCLE = "Cycle";
		public static readonly string FINISH_LINE = "FinishLine";
		public static readonly string PAUSE = "Pause";
		public static readonly string BACK_TO_PLAY = "BackToPlay";
		public static readonly string BACK_TO_MENU = "BackToMenu";
		public static readonly string PLAY_AGAIN = "PlayAgain";
		public static readonly string PLAY_NEXT_LEVEL = "PlayNextLevel";
		public static readonly string RELOADE_LEVEL = "ReloadLevel";
		public static readonly string GOTO_MENU = "GotoMenu";
		public static readonly string SOUND = "Sound";
		public static readonly string SOUND_MUTE = "SoundMute";
		public static readonly string SETTING = "Setting";
		public static readonly string SHUTTER_SLIDE = "ShutterSlide";
		public static readonly string LOADER = "Loader";

		public static class Levels{
			public static readonly string LEVEL0 = "Level0";
			public static readonly string LEVEL1 = "Level1";
			public static readonly string LEVEL2 = "Level2";
			public static readonly string LEVEL3 = "Level3";
			public static readonly string LEVEL4 = "Level4";
			public static readonly string LEVEL5 = "Level5";
			public static readonly string LEVEL6 = "Level6";
			public static readonly string LEVEL7 = "Level7";
			public static readonly string LEVEL8 = "Level8";
			public static readonly string LEVEL9 = "Level9";
		}

		// only for dust world levels
		public static class Dust{
			public static readonly string HAMMER_ACTIVATOR = "HammerActivator";
		}
	}
}

