//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

namespace Assets.Scripts.Misc{

	public class Tags{

		public static readonly string DIE_BLOCK = "DieBlock";
		public static readonly string REPLAY = "Replay";
		public static readonly string CYCLE = "Cycle";
		public static readonly string BACK_TO_MENU = "BackToMenu";
		public static readonly string ROLLER = "Roller";
		public static readonly string HAMMER_CLIP = "HammerClip";
		public static readonly string CHECKPOINT_TRIGGER = "CheckpointTrigger";
		public static readonly string CHECKPOINT_FLAG = "CheckpointFlag";
	}
}

