//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Assets.Scripts.Base;

namespace Assets.Scripts.States{

	public class BeginState : StateBase{

		public BeginState (StateManager sm) : base(sm){

		}

		public override void Init ()
		{
			base.Init ();
			Time.timeScale = 1f;
			manager.SwitchState (new MenuState (manager));
		}
	}
}

