//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Assets.Scripts.Managers;
using Assets.Scripts.Misc;

namespace Assets.Scripts.States{

	public class DustPlay : PlayState{

		public DustPlay (StateManager sm) : base(sm){

		}

		public override void SceneLoaded (int level){
			base.SceneLoaded (level);
			if (StorageManager.IsSoundOn ()) {
				foreach(GameObject hammerClip in GameObject.FindGameObjectsWithTag(Tags.HAMMER_CLIP)){
					hammerClip.GetComponent<AudioSource> ().Play ();
				}
			}
		}

		public override void Pause (){
			base.Pause ();

			foreach (GameObject obj in GameObject.FindGameObjectsWithTag (Tags.HAMMER_CLIP)) {
				Animator animator = obj.GetComponent<Animator> ();
				if(animator != null){
					animator.enabled = false;
				}
			}
		}

		public override void Resume (){
			base.Resume ();

			foreach (GameObject obj in GameObject.FindGameObjectsWithTag (Tags.HAMMER_CLIP)) {
				Animator animator = obj.GetComponent<Animator> ();
				if(animator != null){
					animator.enabled = true;
				}
			}
		}
	}
}

