//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Assets.Scripts.Managers;
using Assets.Scripts.Misc;

namespace Assets.Scripts.States{

	public class NightPlay : PlayState{

		public NightPlay (StateManager sm) : base(sm){

		}

		public override void SceneLoaded (int level){
			base.SceneLoaded (level);

			if (StorageManager.IsSoundOn ()) {

			}
		}
	}
}

