//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Assets.Scripts.Base;
using Assets.Scripts.Misc;
using Assets.Scripts.Managers;

namespace Assets.Scripts.States{

	public class PauseState : StateBase{

		private GameObject pause;
		private GameObject backToPlay;
		private GameObject backToMenu;
		private GameObject cycle;

		public PauseState (StateManager sm) : base(sm){

		}

		public override void Init (){
			base.Init ();

			pause = GameObject.Find (GameCenter.PAUSE);
			backToPlay = GameObject.Find (GameCenter.BACK_TO_PLAY);
			backToMenu = GameObject.Find (GameCenter.BACK_TO_MENU);
			cycle = GameObject.FindWithTag (Tags.CYCLE);

			HidePauseButton ();
			ShowPlayAndMenuButton ();
		}

		public override void MouseDown (GameObject gameObj){
			base.MouseDown (gameObj);

			if (gameObj.name.Equals (GameCenter.BACK_TO_PLAY)) {
				ShowPauseButton ();
				HidePlayAndMenuButton ();
				manager.SwitchState(new PlayState (manager));
				manager.Recycle();
			} 
			else if (gameObj.name.Equals (GameCenter.BACK_TO_MENU)) {
				manager.SwitchState(new BeginState (manager));
				//SceneManager.LoadScene (SceneManager.MENU);
			}
		}

		private void HidePauseButton (){
			cycle.GetComponent<Rigidbody2D> ().isKinematic = true;
			cycle.transform.Find (GameCenter.PIPE).GetComponent<Rigidbody2D> ().isKinematic = true;

			pause.GetComponent<Animator> ().SetBool ("Start", true);
		}

		private void ShowPauseButton (){
			cycle.GetComponent<Rigidbody2D> ().isKinematic = false;
			cycle.transform.Find (GameCenter.PIPE).GetComponent<Rigidbody2D> ().isKinematic = false;
			
			pause.GetComponent<Animator> ().SetBool ("Start", false);
		}

		private void HidePlayAndMenuButton (){

			backToPlay.GetComponent<Animator> ().SetBool ("Start", false);
			backToMenu.GetComponent<Animator> ().SetBool ("Start", false);

			GameObject.Find (GameCenter.LEFT_CONTROL).GetComponent<Animator> ().SetBool ("Start", false);
			GameObject.Find (GameCenter.RIGHT_CONTROL).GetComponent<Animator> ().SetBool ("Start", false);
		}

		private void ShowPlayAndMenuButton (){

			backToPlay.GetComponent<Animator> ().SetBool ("Start", true);
			backToMenu.GetComponent<Animator> ().SetBool ("Start", true);
			GameObject.Find (GameCenter.LEFT_CONTROL).GetComponent<Animator> ().SetBool ("Start", true);
			GameObject.Find (GameCenter.RIGHT_CONTROL).GetComponent<Animator> ().SetBool ("Start", true);
		}
	}
}

