//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using Assets.Scripts.Base;
using Assets.Scripts.Misc;

namespace Assets.Scripts.States{

	public class SceneCloseState : StateBase{

		public SceneCloseState (StateManager sm) : base(sm){

		}

		public override void Init (){
			base.Init ();
			manager.StartCoroutine (LoadScene ());
		}

		IEnumerator LoadScene(){

			GameObject.Find (GameCenter.TOP_SHUTTER).GetComponent<Animator> ().SetBool ("Hiding", false);
			GameObject.Find (GameCenter.BOTTOM_SHUTTER).GetComponent<Animator> ().SetBool ("Hiding", false);

			yield return new WaitForSeconds (1.5f);

			GameObject.Find (GameCenter.LOADER).GetComponent<Animator> ().SetBool ("Hiding", false);

			yield return new WaitForSeconds (2f);
			manager.SwitchState (manager.GetState ());
		}
	}
}

