//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Assets.Scripts.Base;
using Assets.Scripts.Misc;
using Assets.Scripts.Managers;
using Assets.Scripts.States.Night;

namespace Assets.Scripts.States{

	public class WelcomeToNightState : StateBase{

		private GameObject sound;
		private GameObject soundMute;

		public WelcomeToNightState (StateManager sm) : base(sm){

		}

		public override void Init (){
			base.Init ();
			if (! SceneManager.IsSceneLoaded (SceneManager.WELCOME_TO_NIGHT)) {
				SceneManager.LoadScene (SceneManager.WELCOME_TO_NIGHT);
			}
		}

		public override void MouseDown (GameObject gameObj){
			base.MouseDown (gameObj);

			if (gameObj.name.Equals (GameCenter.START)){
				manager.SetState (new NightLevel1 (manager));
				manager.SwitchState(new SceneCloseState(manager));
			}
		}
	}
}

