//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

namespace Assets.Scripts.Managers
{
	public class SceneManager
	{
		public static readonly int MENU = 0;
		public static readonly int SETTING = 1;
		public static readonly int ABOUT = 2;
		public static readonly int WELCOME_TO_NIGHT = 18;

		public static class LevelSelection{
			public static readonly int DUST = 4;
			public static readonly int NIGHT = 5;
			public static readonly int SPRING = 6;
			public static readonly int ICE = 7;
		}

		public static class Dust{
			public static readonly int LEVEL1 = 8;
			public static readonly int LEVEL2 = 9;
			public static readonly int LEVEL3 = 10;
			public static readonly int LEVEL4 = 11;
			public static readonly int LEVEL5 = 12;
			public static readonly int LEVEL6 = 13;
			public static readonly int LEVEL7 = 14;
			public static readonly int LEVEL8 = 15;
			public static readonly int LEVEL9 = 16;
			public static readonly int LEVEL10 = 17;
		}

		public static class Night{
			public static readonly int LEVEL1 = 19;
			public static readonly int LEVEL2 = 20;
			public static readonly int LEVEL3 = 21;
			public static readonly int LEVEL4 = 22;
			public static readonly int LEVEL5 = 23;
			public static readonly int LEVEL6 = 24;
			public static readonly int LEVEL7 = 25;
			public static readonly int LEVEL8 = 26;
			public static readonly int LEVEL9 = 27;
			public static readonly int LEVEL10 = 28;
		}

		public static void LoadScene(int scene){
			Application.LoadLevel (scene);
		}

		public static void ReloadScene (){
			Application.LoadLevelAsync (Application.loadedLevel);
		}

		public static bool IsSceneLoaded(int scene){
			if (Application.loadedLevel == scene) {
				return true;
			} else {
				return false;
			}
		}
	}
}

