//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

namespace Assets.Scripts.Managers
{
	public class SceneManager
	{
		public static readonly int MENU = 0;

		public static class Dust{
			public static readonly int LEVEL1 = 8;
			public static readonly int LEVEL2 = 9;
		}

		public static void LoadScene(int scene){
			Application.LoadLevel (scene);
		}

		public static void ReloadScene (){
			Application.LoadLevel (Application.loadedLevel);
		}

		public static bool IsSceneLoaded(int scene){
			if (Application.loadedLevel == scene) {
				return true;
			} else {
				return false;
			}
		}
	}
}

